name = "rander"
main = "src/index.js"
compatibility_date = "2024-05-17"
 
node_compat = true
workers_dev = false
route = { pattern = "rander.moxen.cn/*", zone_name = "moxen.cn" }
 
r2_buckets  = [
  { binding = "imagesR2", bucket_name = "images"},
]
 
kv_namespaces = [
    { binding = "imagesCache", id = "177da2d4b393427783aab9837b010b1d" }
]
 
[placement]
mode = "smart"
